name = "search-api"
main = "src/index.js"
compatibility_date = "2025-04-01"

[vars]
GOOGLE_CLIENT_ID = "YOUR_GOOGLE_CLIENT_ID"

[[d1_databases]]
binding = "DB"
database_name = "search-db"
database_id = "8ef70bdc-dd5b-4c36-a14e-35b550da6c7c"
migrations_dir = "migrations"
